language: scala

dist: trusty

group: edge

jdk:
- oraclejdk8

script:
- "./ci.sh $CI_TEST"

install:
  - pip install --user codecov

env:
  matrix:
    - CI_TEST: "unit"
    - CI_TEST: "slow"
    - CI_TEST: "scalafmt"

cache:
  directories:
  - "$HOME/.sbt/0.13/dependency"
  - "$HOME/.sbt/boot/scala*"
  - "$HOME/.sbt/launchers"
  - "$HOME/.ivy2/cache"
  - "$HOME/.coursier"

before_cache:
- du -h -d 1 $HOME/.ivy2/cache
- du -h -d 2 $HOME/.sbt/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
- rm -rf $HOME/.ivy2/local


